 - hosts: all
   gather_facts: false
   tasks:
   #- name: file doesnt exist, but i dont care .. file plugin itself warns anyways ...
   #  debug: msg="{{ lookup('file', './template.csv', errors='ignore') }}"
   - name: Using CSV Module
     read_csv:
       path: ./template.csv
       
     register: users
   - debug:
        msg: 'User {{ users.dict.dag.name }} has UID {{ users.dict.dag.uid }} and GID {{ users.dict.dag.gid }}'
   #tasks:
   #- name: test 
   #  shell: "pwd"
   
   #- name: File Stat
    # file:
     #  path: ./template.yml
      # mode: '0446'
       #owner: root
